version: 2.1
jobs:
  install_deps:
    working_directory: ~/project
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  lint:
    working_directory: ~/project
    docker:
      - image: cimg/node:17.4.0
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Lint
          command: npm run test:lint
  test:
    working_directory: ~/project
    docker:
        - image: cimg/node:17.4.0
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Tests
          command: npm run test
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:17.4.0
    steps:
      #- checkout
      #- run:
      #    name: Update NPM
      #    command: "sudo npm install -g npm"
      #- restore_cache:
      #    key: dependency-cache-{{ checksum "package-lock.json" }}
      #- run:
      #    name: Install Dependencies
      #    command: npm install
      #- save_cache:
      #    key: dependency-cache-{{ checksum "package-lock.json" }}
      #    paths:
      #      - ./node_modules
      #- run:
      #    name: Tests
      #    command: npm run test
      #- restore_cache:
      #    key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Webpack Compile
          command: npm run start:webpack
workflows:
  version: 2.1
  test_and_build:
    jobs:
      - install_deps
      - lint
      - test
      - build