version: 2.1
working_directory: root/project
jobs:
  install_deps:
    docker:
      - image: cimg/node:17.4.0
    steps:
        - checkout
        - run:
            name: Update NPM
            command: "sudo npm install -g npm"
        - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: Install Dependencies
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
  lint:
    docker:
        - image: cimg/node:17.4.0
    steps:
      - run:
          name: Lint
          command: npm run test:lint
  test:
    docker:
        - image: cimg/node:17.4.0
    steps:
      - run:
          name: Tests
          command: npm run test
  build:
    # working_directory: ~/project
    docker:
      - image: cimg/node:17.4.0
    steps:
      # - run:
          # name: Update NPM
          # command: "sudo npm install -g npm"
      # - restore_cache:
          # key: dependency-cache-{{ checksum "package-lock.json" }}
      # - run:
          # name: Install Dependencies
          # command: npm install
      # - save_cache:
          # key: dependency-cache-{{ checksum "package-lock.json" }}
          # paths:
            # - ./node_modules
      # - run:
      #     name: Tests
      #     command: npm run test
      - run:
          name: Start the app
          command: npm run start:webpack